#!/bin/bash
cd /tmp/rom # Depends on where source got synced
rm -rf .repo & # lets remove unnecessary things, so that no storage issue can occur

# Normal build steps
source build/envsetup.sh
lunch omni_tissot-eng
mka recoveryimage

  ZIP=$(ls out/target/product/tissot/OrangeFox*.zip)
curl https://free.keep.sh/$ZIP --data-binary @$ZIP
