#!/bin/bash
apt-get -y update && apt-get -y upgrade && apt-get -y install bc bison build-essential curl flex g++-multilib gcc gcc-multilib clang git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libwxgtk3.0-dev libxml2 libxml2-utils lzop pngcrush schedtool squashfs-tools xsltproc zip zlib1g-dev unzip openjdk-8-jdk python ccache libtinfo5 repo libstdc++6 wget libssl-dev rsync
git config --global user.name "Unknownbitch07"
git config --global user.email "sufiyanmp07@gmail.com"
git config --global color.ui false
git clone https://github.com/akhilnarang/scripts && cd scripts && bash setup/android_build_env.sh && cd ..

mkdir -p /tmp/rom # Where to sync source
cd /tmp/rom

repo init --depth=1 -u https://gitlab.com/OrangeFox/Manifest.git -b fox_9.0
repo sync --force-sync
git clone https://github.com/Unknownbitch07/orangefox_device_xiaomi_tissot device/xiaomi/tissot/
rm -rf bootable/recovery
git clone https://gitlab.com/OrangeFox/bootable/Recovery.git -b fox_9.0 bootable/recovery
rm -rf hardware/qcom/bootctrl

