#!/bin/bash

mkdir -p /tmp/rom # Where to sync source
cd /tmp/rom

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice. Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
# I want to sync aex source!
repo init -q --no-repo-verify --depth=1 -u git://github.com/Palladium-OS/platform_manifest.git -b 11 -g default,-device,-mips,-darwin,-notdefault

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 30 || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 8

# Clone Device Sources
git clone --depth=1 https://github.com/ShapeShiftOS-Devices/device_xiaomi_msm8953-common.git -b 11.0 device/xiaomi/msm8953-common
git clone --depth=1 https://github.com/Hmm0/android_device_xiaomi_tissot.git -b eleven device/xiaomi/tissot
git clone --depth=1 https://github.com/Unknownbitch07/android_kernel_xiaomi_msm8953.git -b 11.0 kernel/xiaomi/msm8953
git clone https://gitlab.com/MASTERGUY/proprietary_vendor_xiaomi.git -b eleven vendor/xiaomi --single-branch --depth=1

#hals
rm -rf hardware/qcom-caf/display hardware/qcom-caf/media hardware/qcom-caf/audio
rm -rf hardware/qcom-caf/msm8996/display hardware/qcom-caf/msm8996/audio hardware/qcom-caf/msm8996/media
git clone https://github.com/crdroidandroid/android_hardware_qcom_display.git -b 11.0-caf-msm8996 hardware/qcom-caf/msm8996/display
git clone https://github.com/crdroidandroid/android_hardware_qcom_media.git -b 11.0-caf-msm8996 hardware/qcom-caf/msm8996/media
git clone https://github.com/LineageOS/android_hardware_qcom_audio -b lineage-18.0-caf-msm8996 hardware/qcom-caf/msm8996/audio

# Source Fixing
rm -rf hardware/qcom-caf/wlan
git clone https://github.com/ArrowOS/android_hardware_qcom_wlan.git -b arrow-11.0-caf hardware/qcom-caf/wlan

